@echo off
echo Starting Capacitor Setup...
echo Initializing NPM...
call npm init -y
echo Installing Dependencies...
call npm install "@capacitor/core" "@capacitor/android"
call npm install -D "@capacitor/cli"
echo Initializing Capacitor...
call npx cap init IsteApp com.iste.app --web-dir www
echo Adding Android...
call npx cap add android
echo Done!
