@echo off
echo Starting Capacitor Setup...
echo Initializing NPM...
call npm init -y
echo Installing Dependencies...
call npm install
echo Initializing Capacitor...
echo Adding Android...
call npm run build
call mkdir www/
call cp *.html www
call npx cap add android
call npx cap sync android
echo Done!
